### ISSUE TITLE
2016/05/10

### ISSUE THREAD

**Issue by shikakun** [haseoyeon/500-sorry#1]
@haseoyeon (Cc: @kenchan )
Slack で相談いただいたので、コードを確認して調べてみました！

## 問題

Slack で相談していただいた問題は、以下の通りでした。

#### スマホ版の問題

```
SPは（左が今の状況で、右が構成です）
1.線とイラストの間と文章と下にあるCopyrightの間も余白が余白 部分が 生じます。
2.内容部分の外側に枠を作りたいです。
3.copyright 部分に背景いれたいです。
```

<div align="center"><table><tr><td><img src="https://cloud.githubusercontent.com/assets/1396953/15134174/ab77da64-16a4-11e6-97e7-9ba6eeb49a8f.png"></td></tr></table></div>

#### PC 版の問題

```
PCは（上が構成で、下が今の状況です）
1.ロゴとタイトルを一直線上に配置したいです。
2.内容部分の外側に枠を作りたいです。
3.copyright 部分に背景いれたいです。
```

<div align="center"><table><tr><td><img src="https://cloud.githubusercontent.com/assets/1396953/15134177/b1fa2748-16a4-11e6-956a-fae35f0422b4.png"></td></tr></table></div>

## 調べる

まず、要素の始まりと終わりがどこにあるのかよくわからなかったので、インデントを揃えてみました！

#### HTML

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
  </head>
  <body>
    <header class="header">
      <img class="hearder-img" src="images/01.png">
      <div class="site-title">
        <p class="site-title">
          ハンドメイド作品が売買できるWEBマーケット
        </p>
        <p class="site-title-sub"></p>       　
      </div>
    </header>
    <div class="contents">
      <img class="illust" src="images/illust.png">
      <div class="text">
        <div class="text-contents">
          <h3>
            お探しのページを表示できません
          </h3>
          <p>
            ご不便おかけして申し訳ございません。
          </p>
          <p>
            ただいま問題の解決に取り組んでおります。お手数ですが、しばらく時間を置いてから再度お試しください。
          </p>
          <p class="contact-text">
            時間を置いても表示されない場合は、お手数ですがユーザーサポートまで<a href="https://tetote-market.jp/help/" target="_blank">お問い合わせ</a>下さい。
          </p>
        </div>
      </div>
    </div>
    <footer class="footer">
      <p class="site-title-sub"></p>
      <p>Copyright © GMO Pepabo OC, Inc.All Rights Reserved.</p>
    </footer>
  </body>
</html>
```

#### CSS

```css
@charset "UTF-8";
.body {
  background: #fbf8f5;
}
.header {
  font-family: Raleway, "Hiragino Kaku Gothic ProN",  Meiryo,  sans-serif;
}
.header {
  padding: 20px;
}
.hearder-img {
  margin-right: 460px;
}
.site-title {
  text-align: center;
  margin-left: 0px;
}
.site-title-sub {
  height: 2px;
  background-color: #5a3932;
  vertical-align: bold;
  margin: auto;
  letter-spacing: 1px;
}
.contents {
  padding: 26px;
}
.illust {
  width: 100%;
}
.text-contents {
  color: #5a3932;
}
.contact-wrapper {
  margin-top: 230px;
}
.contact-text {
  text-align: left;
  font-size: 0.85rem;
  background: #ffffff;
  color: #BD8384;
}
a:link {
  text-decoration: none;
  color: #5a3932;
}
a:visited {
  text-decoration: none;
  color: #5a3932;
}
a:active {
  text-decoration: none;
  color: #5a3932;
}
a:hover {
  text-decoration: underline;
  color: red;
}
.footer {
  font-size: 0.8rem;
  margin-top: 320px;
  color: #656867;
  text-align: center;
}

@media screen and (min-width: 768px) {
  .header {
    text-align: center;
    font-family: Raleway, "Hiragino Kaku Gothic ProN",  Meiryo,  sans-serif;
  }
  .site-title {
    color: #5a3932;
    margin-right: 0px;
  }
  .site-title-sub {
    margin-top: 10px;
    width: 56%;
    align-content: center;
  }
  .contents {
    width: 730px;
    padding: 0;
    margin: 0 auto;
  }
  .illust {
    float: right;
    width: 50%;
  }
  .text {
    float: left;
    width: 50%;
  }
  .text-contents {
    padding-left: 20px;
  }
}

```

うーん、こうして眺めてみると、「問題」に挙がってることが引き起こされそうな原因が見えてきました。

* `<div class="site-title">` のなかに、同じ class 名の `<p class="site-title">` があって、どちらにも同じスタイルが適用されている。
  * 同じスタイルシートが意図せず複数の要素に適用されてしまうと、表示が崩れる原因になります。
* 内容が空っぽの `<p class="site-title-sub"></p>` がある。
  * 必要ない要素があると、表示が崩れる原因になります。

さらに、次のように考えてみました。

* まずは、PC 版のことは忘れて、スマホ版だけを完成させるコーディングをするのはどうでしょうか。
  * スマホ版のスタイルシートを変更すると、PC 版の表示にも影響します。だから、同時に作業せず、まずはスマホ版で表示が崩れていないようにして、それから Media Queries を利用して PC 版をコーディングしたほうが、効率よくうまくいくはずです。

あまり直接的に原因を解説したわけではなくてすみませんが、ここまで確認お願いします！

（さらに、仕事に関する HTML や CSS は、できれば会社の GitHub にリポジトリを作って作業をしたほうが、良いかもしれません…！）
